#!/usr/bin/perl

if ($#ARGV != 1) {
    die "Usage: process-grabber experiment-name file";
}

$exp_name = $ARGV[0];
$file=$ARGV[1];

print "#h exp value\n";

open(FILE, "$file") || die "Couldn't open $file:$!";

$value = "";
while (<FILE>) {
    if (/^iterations.unit time = (\d+).(\d+)/) {
        $value = "$value, $1.$2";
    }
}
print STDOUT "$value\n";
close(FILE);

exit 0;
